version: 0.0
os: linux
files:
  - source: css/
    destination: /var/www/html/
    overwrite: true
  - source: images/
    destination: /var/www/html/
    overwrite: true
  - source: js/
    destination: /var/www/html/
    overwrite: true
  - source: fonts/
    destination: /var/www/html/
    overwrite: true
  - source: mail/
    destination: /var/www/html/
    overwrite: true
  - source: /blog-single-sidebar.html
    destination: /var/www/html/
    overwrite: true
  - source: /cart.html
    destination: /var/www/html/
    overwrite: true
  - source: /checkout.html
    destination: /var/www/html/
    overwrite: true
  - source: /contact.html
    destination: /var/www/html/
    overwrite: true
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
  - source: /style.css
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install_dependencies.sh
          pattern: "*"
          mode: +x
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install.sh
          pattern: "*"
          mode: +x
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/start_server.sh
          pattern: "*"
          mode: +x
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/stop_server.sh
          pattern: "*"
          mode: +x