version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install_dependencies.sh
          pattern: "*"
          mode: +x
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
      permissions:
        - object: scripts/install.sh
          pattern: "*"
          mode: +x
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/start_server.sh
          pattern: "*"
          mode: +x
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
      permissions:
        - object: scripts/stop_server.sh
          pattern: "*"
          mode: +x