version: 0.0
os: linux
files:
  - source: css/
    destination: /var/www/html/
  - source: images/
    destination: /var/www/html/
  - source: js/
    destination: /var/www/html/
  - source: mail/
    destination: /var/www/html/
  - source: blog-single-sidebar.html
    destination: /var/www/html/
  - source: cart.html
    destination: /var/www/html/
  - source: checkout.html
    destination: /var/www/html/
  - source: contact.html
    destination: /var/www/html/
  - source: index.html
    destination: /var/www/html/
  - source: style.css
    destination: /var/www/html/
  - source: appspec.yml
    destination: /home/ubuntu
  - source: scripts/
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

