version: 0.0
os: linux
files:
#shouldworknow
  - source: /cart.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
      permissions: +x
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
      permissions: +x